version: '3.8'

# Production-Ready LexOS Docker Compose Configuration
# Enhanced with monitoring, scaling, security, and H100 optimization

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 40s

services:
  # =================
  # OLLAMA SERVICE
  # =================
  ollama:
    image: ollama/ollama:latest
    container_name: lexos-ollama
    hostname: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./models:/models:ro  # Pre-loaded models
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_NUM_PARALLEL=${OLLAMA_PARALLEL:-4}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_MODELS:-10}
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-5m}
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_DEVICE_ID:-0}']  # Specific GPU selection
              capabilities: [gpu]
        limits:
          memory: ${OLLAMA_MEMORY_LIMIT:-32G}
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=ollama"
      - "com.lexos.description=Model inference service"

  # =================
  # CHROMADB SERVICE
  # =================
  chromadb:
    image: chromadb/chroma:latest
    container_name: lexos-chromadb
    hostname: chromadb
    ports:
      - "${CHROMA_PORT:-8000}:8000"
    volumes:
      - chroma-data:/chroma/chroma
      - ./chroma-config:/config:ro
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${CHROMA_TELEMETRY:-false}
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_AUTH:-none}
      - CHROMA_SERVER_AUTH_TOKEN=${CHROMA_TOKEN:-}
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=chromadb"
      - "com.lexos.description=Vector database for memories"

  # =================
  # REDIS SERVICE
  # =================
  redis:
    image: redis:7-alpine
    container_name: lexos-redis
    hostname: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-lexos_secret}
      --maxmemory ${REDIS_MEMORY:-2gb}
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfsync everysec
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=redis"
      - "com.lexos.description=Cache and message broker"

  # =================
  # POSTGRESQL SERVICE
  # =================
  postgres:
    image: postgres:15-alpine
    container_name: lexos-postgres
    hostname: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-lexos}
      - POSTGRES_USER=${POSTGRES_USER:-lexos}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-lexos_secret}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-lexos} -d ${POSTGRES_DB:-lexos}"]
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=postgres"
      - "com.lexos.description=Persistent storage for system state"

  # =================
  # LEXOS MAIN SERVICE
  # =================
  lexos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.11}
        - INSTALL_CONSCIOUSNESS=${ENABLE_CONSCIOUSNESS:-false}
      cache_from:
        - lexos:latest
    image: lexos:latest
    container_name: lexos-brain
    hostname: lexos
    ports:
      - "${LEXOS_PORT:-8080}:8080"
      - "${LEXOS_WS_PORT:-8081}:8081"  # WebSocket port
    volumes:
      - ./lexos_memory:/app/lexos_memory
      - ./logs:/app/logs
      - ./configs:/app/configs
      - ./uploads:/app/uploads
      - ./static:/app/static:ro
      - ./backups:/app/backups
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For container management
    environment:
      # Ollama Configuration
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_TIMEOUT=${OLLAMA_TIMEOUT:-300}
      
      # ChromaDB Configuration
      - CHROMA_HOST=http://chromadb:8000
      - CHROMA_TOKEN=${CHROMA_TOKEN:-}
      
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-lexos_secret}
      
      # PostgreSQL Configuration
      - DATABASE_URL=postgresql://${POSTGRES_USER:-lexos}:${POSTGRES_PASSWORD:-lexos_secret}@postgres:5432/${POSTGRES_DB:-lexos}
      
      # LexOS Configuration
      - LEXOS_ENV=${LEXOS_ENV:-production}
      - LEXOS_DEBUG=${LEXOS_DEBUG:-false}
      - LEXOS_LOG_LEVEL=${LEXOS_LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      
      # Performance Settings
      - MAX_WORKERS=${MAX_WORKERS:-4}
      - MAX_CONCURRENT_TASKS=${MAX_CONCURRENT_TASKS:-5}
      - ENABLE_CONSCIOUSNESS=${ENABLE_CONSCIOUSNESS:-false}
      
      # Security
      - API_KEY=${API_KEY:-}
      - JWT_SECRET=${JWT_SECRET:-change_me_in_production}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      
      # GPU Settings
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      
    depends_on:
      ollama:
        condition: service_healthy
      chromadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: ${LEXOS_MEMORY_LIMIT:-16G}
          cpus: '${LEXOS_CPU_LIMIT:-4}'
        reservations:
          memory: ${LEXOS_MEMORY_RESERVE:-8G}
          cpus: '${LEXOS_CPU_RESERVE:-2}'
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=main"
      - "com.lexos.description=Core LexOS brain service"
      - "traefik.enable=true"
      - "traefik.http.routers.lexos.rule=Host(`${LEXOS_DOMAIN:-lexos.local}`)"
      - "traefik.http.services.lexos.loadbalancer.server.port=8080"

  # =================
  # MONITORING STACK
  # =================
  prometheus:
    image: prom/prometheus:latest
    container_name: lexos-prometheus
    hostname: prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    logging: *default-logging
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=prometheus"
      - "com.lexos.description=Metrics collection"

  grafana:
    image: grafana/grafana:latest
    container_name: lexos-grafana
    hostname: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=redis-datasource
      - GF_SERVER_ROOT_URL=http://${LEXOS_DOMAIN:-localhost}:${GRAFANA_PORT:-3000}
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - prometheus
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=grafana"
      - "com.lexos.description=Monitoring dashboards"

  # =================
  # REVERSE PROXY
  # =================
  traefik:
    image: traefik:v2.10
    container_name: lexos-traefik
    hostname: traefik
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
      - "${TRAEFIK_DASHBOARD_PORT:-8082}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml:ro
      - traefik-certs:/certs
    environment:
      - TRAEFIK_API_INSECURE=${TRAEFIK_INSECURE:-true}
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL:-INFO}
    restart: unless-stopped
    logging: *default-logging
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=traefik"
      - "com.lexos.description=Reverse proxy and load balancer"

  # =================
  # BACKUP SERVICE
  # =================
  backup:
    image: offen/docker-volume-backup:latest
    container_name: lexos-backup
    hostname: backup
    volumes:
      - ollama-data:/backup/ollama-data:ro
      - chroma-data:/backup/chroma-data:ro
      - postgres-data:/backup/postgres-data:ro
      - redis-data:/backup/redis-data:ro
      - ./lexos_memory:/backup/lexos_memory:ro
      - ./backups:/archive
    environment:
      - BACKUP_CRON_EXPRESSION=${BACKUP_CRON:-0 3 * * *}  # Daily at 3 AM
      - BACKUP_FILENAME=lexos-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_ARCHIVE=/archive
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION:-7}
      - BACKUP_STOP_DURING_BACKUP_CONTAINER_LABEL=com.lexos.backup-stop
      - AWS_S3_BUCKET_NAME=${S3_BUCKET:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY:-}
    restart: unless-stopped
    logging: *default-logging
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=backup"
      - "com.lexos.description=Automated backup service"

  # =================
  # LOG AGGREGATION
  # =================
  loki:
    image: grafana/loki:latest
    container_name: lexos-loki
    hostname: loki
    ports:
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/config.yml
    restart: unless-stopped
    logging: *default-logging
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=loki"
      - "com.lexos.description=Log aggregation"

  promtail:
    image: grafana/promtail:latest
    container_name: lexos-promtail
    hostname: promtail
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml:ro
      - ./logs:/var/log/lexos:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - loki
    networks:
      - lexos-network
    labels:
      - "com.lexos.service=promtail"
      - "com.lexos.description=Log collector"

# =================
# NETWORKS
# =================
networks:
  lexos-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.name: lexos-br
    labels:
      - "com.lexos.network=main"

# =================
# VOLUMES
# =================
volumes:
  # Core data volumes
  ollama-data:
    driver: local
    labels:
      - "com.lexos.volume=ollama-models"
  chroma-data:
    driver: local
    labels:
      - "com.lexos.volume=vector-database"
  postgres-data:
    driver: local
    labels:
      - "com.lexos.volume=relational-database"
  redis-data:
    driver: local
    labels:
      - "com.lexos.volume=cache"
  
  # Monitoring volumes
  prometheus-data:
    driver: local
    labels:
      - "com.lexos.volume=metrics"
  grafana-data:
    driver: local
    labels:
      - "com.lexos.volume=dashboards"
  loki-data:
    driver: local
    labels:
      - "com.lexos.volume=logs"
  
  # Infrastructure volumes
  traefik-certs:
    driver: local
    labels:
      - "com.lexos.volume=certificates"

# =================
# ADDITIONAL FILES NEEDED
# =================
# 
# 1. .env file with all the environment variables
# 2. Dockerfile for LexOS
# 3. monitoring/prometheus.yml for metrics configuration
# 4. monitoring/grafana/provisioning/ for dashboard setup
# 5. monitoring/loki-config.yml for log aggregation
# 6. monitoring/promtail-config.yml for log collection
# 7. traefik/traefik.yml for reverse proxy config
# 8. postgres-init/ with initialization scripts
