# LexOS Configuration File
version: 1.0

system:
  name: "LexOS"
  description: "Personal AI Operating System"

performance:
  max_concurrent_tasks: 5
  task_queue_size: 100
  worker_threads: 4

security:
  enable_auth: true
  admin_password: "changeme" # Change in production!
  allowed_origins: ["*"]
  csrf_protection: true

backup:
  enabled: true
  backup_dir: "backups"
  retention_days: 30

alerting:
  enable_alerts: true
  email: "alerts@example.com"
  webhook_url: "https://hooks.example.com/lexos"
  alert_on:
    - "system_error"
    - "memory_exceeded"
    - "gpu_overload"

models:
  strategy: "adaptive"
  assignments:
    chat:
      primary: "llama3.2:3b"
      fallback: ["llama3.2:1b", "mistral:7b"]
    code:
      primary: "qwen2.5-coder:32b"
      fallback: ["deepseek-coder:33b", "codellama:34b"]
    vision:
      primary: "llava:34b"
      fallback: ["llava:7b", "bakllava:7b"]
    reasoning:
      primary: "deepseek-r1:7b"
      fallback: ["mistral:7b-instruct", "llama3.3:70b-instruct-q4_K_M"]
    research:
      primary: "llama3.3:70b-instruct-q4_K_M"
      fallback: ["mixtral:8x7b", "llama3.2:3b"]

memory:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  chunk_size: 512
  chunk_overlap: 50
  consolidation_interval: 300
  importance_threshold: 0.7
  max_memories: 10000
  working_memory_size: 50
  short_term_duration: 3600

learning:
  enabled: true
  track_metrics: true
  learning_rate: 0.1
  adapt_model_selection: true
  performance_window: 100
  pattern_detection: true
  min_pattern_occurrences: 3

consciousness:
  enabled: true
  awareness_update_interval: 10
  reflection_interval: 300
  self_monitoring: true
  goal_tracking: true
  emotion_simulation: false

web_interface:
  enabled: true
  port: 8080
  host: "0.0.0.0"
  enable_auth: true
  allowed_origins: ["*"]
  enable_chat: true
  enable_monitoring: true
  enable_file_upload: true
  max_upload_size: 100

cli_interface:
  enabled: true
  enable_autocomplete: true
  history_size: 1000
  use_colors: true
  use_rich_output: true

monitoring:
  monitor_interval: 30
  track_cpu: true
  track_memory: true
  track_gpu: true
  track_disk: true
  enable_alerts: true
  alert_cpu_threshold: 90
  alert_memory_threshold: 85
  alert_gpu_threshold: 95

logging:
  level: "INFO"
  main_log: "logs/lexos.log"
  error_log: "logs/errors.log"
  performance_log: "logs/performance.log"
  max_size: "100MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

extensions:
  enable_plugins: true
  plugin_directory: "plugins"
  auto_load: true
  plugins:
    - name: "web_search"
      enabled: false
    - name: "file_system"
      enabled: true
    - name: "calendar"
      enabled: false